/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.abas.test;

import org.junit.Test;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;
import static org.junit.Assert.assertTrue;

public class LibraryTest {

	@Test
	public void testSomeLibraryMethod() {
		Library classUnderTest = new Library();
		assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
	}

	@Test
	public void canGreetWithSpecificName() {
		Library library = new Library();
		assertThat(library.helloWorld("Benny"), is("Hello, Jasmin!"));
	}

}
