/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.abas.test;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public String helloWorld(String name) {
        return "Hello, " + name + "!";
    }
}
